version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: multidb-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: MultiDBAcademy
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  mysql_data:
